# Generated by Django 2.0.2 on 2018-03-09 03:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('brand', models.CharField(blank=True, max_length=32, verbose_name='品牌')),
                ('install_location', models.CharField(choices=[('cage', '电梯轿箱'), ('machine_room', '电梯机房'), ('hall', '电梯大厅'), ('other', '其他位置')], default='other', max_length=32, verbose_name='安装位置')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('account', models.CharField(max_length=32, verbose_name='登录帐号')),
                ('password', models.CharField(max_length=32, verbose_name='登录密码')),
                ('rtsp_src', models.CharField(max_length=128, verbose_name='rtsp源地址')),
                ('rtmp_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='rtmp播放地址')),
                ('stream_pushed', models.BooleanField(default=False, verbose_name='是否已开启推流')),
                ('ffmpeg_pid', models.IntegerField(blank=True, editable=False, null=True, verbose_name='ffmpeg进程id')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, verbose_name='使用编号')),
                ('type', models.CharField(choices=[('elevator', '直梯'), ('escalator', '扶梯')], default='直梯', max_length=9, verbose_name='梯型')),
                ('sn', models.CharField(max_length=20, unique=True, verbose_name='注册代码')),
                ('maintenance_org', models.CharField(blank=True, max_length=128, verbose_name='维保单位')),
                ('manufacturer', models.CharField(blank=True, max_length=64, verbose_name='制造厂家')),
                ('product_model', models.CharField(blank=True, max_length=64, verbose_name='产品型号')),
                ('start_using_date', models.DateField(blank=True, null=True, verbose_name='投入使用时间')),
                ('control_mode', models.CharField(blank=True, max_length=32, verbose_name='控制类型')),
                ('main_motor_power', models.CharField(blank=True, max_length=64, verbose_name='主电机功率')),
                ('lifting_height', models.CharField(blank=True, max_length=64, verbose_name='提升高度')),
                ('rated_speed', models.CharField(blank=True, max_length=64, verbose_name='额定速度')),
                ('rated_load', models.CharField(blank=True, max_length=64, verbose_name='额定载重')),
                ('lng', models.CharField(blank=True, max_length=64, verbose_name='经度')),
                ('lat', models.CharField(blank=True, max_length=64, verbose_name='纬度')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='下次检验日期')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='采集板ip地址')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('base_station', models.CharField(blank=True, default=1, max_length=32, verbose_name='基站楼层')),
                ('station_mapping_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None, verbose_name='层站名称映射表')),
                ('step_width', models.CharField(blank=True, max_length=64, verbose_name='梯级宽度')),
                ('transport_capacity', models.CharField(blank=True, max_length=64, verbose_name='输送能力')),
                ('use_segment_length', models.CharField(blank=True, max_length=64, verbose_name='使用区段长度')),
                ('tilt_angle', models.CharField(blank=True, max_length=64, verbose_name='倾斜角')),
                ('handrail_length', models.CharField(blank=True, max_length=64, verbose_name='扶手带长度')),
                ('handrail_size', models.CharField(blank=True, max_length=64, verbose_name='扶手带尺寸')),
                ('door_open_mode', models.CharField(blank=True, max_length=32, verbose_name='开门形式')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='层数')),
                ('station', models.PositiveIntegerField(blank=True, null=True, verbose_name='站数')),
                ('pit_depth', models.CharField(blank=True, max_length=64, verbose_name='底坑深度')),
                ('traction_machine_model', models.CharField(blank=True, max_length=64, verbose_name='曳引机型号')),
                ('speed_limiter_model', models.CharField(blank=True, max_length=64, verbose_name='限速器型号')),
                ('traction_wheel_diameter', models.CharField(blank=True, max_length=64, verbose_name='曳引轮直径')),
                ('landing_door_size', models.CharField(blank=True, max_length=64, verbose_name='厅门规格')),
                ('cable_diameter', models.CharField(blank=True, max_length=64, verbose_name='钢丝绳直径')),
                ('buffer_model', models.CharField(blank=True, max_length=64, verbose_name='缓冲器型号')),
                ('door_open_width', models.CharField(blank=True, max_length=64, verbose_name='开门宽度')),
                ('top_floor_height', models.CharField(blank=True, max_length=64, verbose_name='顶层高度')),
                ('reducer_speed_ratio', models.CharField(blank=True, max_length=64, verbose_name='减速机速比')),
                ('main_motor_speed', models.CharField(blank=True, max_length=64, verbose_name='主电机转速')),
                ('speed_limiter_action_speed', models.CharField(blank=True, max_length=64, verbose_name='限速器动作速度')),
                ('door_motor_model', models.CharField(blank=True, max_length=64, verbose_name='门机型号')),
                ('cage_size', models.CharField(blank=True, max_length=64, verbose_name='轿箱尺寸')),
                ('safety_gea_model', models.CharField(blank=True, max_length=64, verbose_name='安全钳型号')),
                ('well_size', models.CharField(blank=True, max_length=64, verbose_name='井道尺寸')),
                ('usage', models.CharField(blank=True, max_length=64, verbose_name='电梯用途')),
                ('door_control_system_type', models.CharField(blank=True, max_length=64, verbose_name='门控系统类型')),
                ('have_power_failure_reflatfloor', models.BooleanField(default=False, verbose_name='断电再平层装置')),
                ('have_energy_feedback_system', models.BooleanField(default=False, verbose_name='有能量回馈系统')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elevators', to='base.Area', verbose_name='安装区域')),
                ('charge_ppl', models.ManyToManyField(blank=True, related_name='charged_elevators', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '电梯',
                'verbose_name_plural': '电梯',
                'db_table': 'elevator',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('hx_id', models.CharField(blank=True, max_length=64, verbose_name='环信ID')),
                ('install_location', models.CharField(blank=True, choices=[('cage', '轿箱'), ('other', '其他')], default='cage', max_length=16, verbose_name='安装位置')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Elevator', verbose_name='所属电梯')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '显示终端',
                'verbose_name_plural': '显示终端',
                'db_table': 'terminal',
            },
        ),
    ]
