# Generated by Django 2.0.2 on 2018-03-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('device', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='maintenance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.MaintenancePlan'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='maintenance_ppl',
            field=models.ManyToManyField(blank=True, related_name='maintain_elevators', to=settings.AUTH_USER_MODEL, verbose_name='维保人员'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='camera',
            name='elevator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='device.Elevator', verbose_name='所属电梯'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户'),
        ),
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='elevator',
            unique_together={('tenant', 'name')},
        ),
    ]
