# Generated by Django 2.0.2 on 2018-03-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('certificate_number', models.CharField(max_length=128, unique=True, verbose_name='证书编号')),
                ('file', models.FileField(upload_to='certificate', verbose_name='附件')),
            ],
            options={
                'verbose_name': '电梯准用证',
                'verbose_name_plural': '电梯准用证',
                'db_table': 'elevator_certificate',
            },
        ),
        migrations.CreateModel(
            name='OperationCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('certificate_number', models.CharField(max_length=128, unique=True, verbose_name='证书编号')),
                ('file', models.FileField(upload_to='user_license', verbose_name='附件')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属人员')),
            ],
            options={
                'verbose_name': '人员操作证',
                'verbose_name_plural': '人员操作证',
                'db_table': 'operation_certificate',
            },
        ),
    ]
