# Generated by Django 2.0.2 on 2018-03-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('routing_inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinginspectionrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='routinginspectionrecord',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='routinginspectionrecord',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='routinginspectionrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户'),
        ),
    ]
