# Generated by Django 2.0.2 on 2018-03-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('opt_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='运行次数')),
                ('travel_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='运行趟数')),
                ('door_open_close_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='开关门次数')),
                ('rope_bend_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='钢丝绳弯折次数')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Elevator', verbose_name='所属电梯')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '运行统计数据',
                'verbose_name_plural': '运行统计数据',
                'db_table': 'run_data_record',
            },
        ),
    ]
