# Generated by Django 2.0.2 on 2018-03-09 03:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=False, verbose_name='生效')),
                ('enable_sms_message_notify', models.BooleanField(verbose_name='启用短信提示')),
                ('enable_app_message_push', models.BooleanField(verbose_name='启用app消息推送')),
                ('elevator', models.ManyToManyField(blank=True, to='device.Elevator', verbose_name='适用电梯')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '告警策略',
                'verbose_name_plural': '告警策略',
                'db_table': 'alarm_policy',
            },
        ),
        migrations.CreateModel(
            name='FaultRecord',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='故障编号')),
                ('record_from', models.CharField(blank=True, choices=[('电话报修', '电话报修'), ('班组自查', '班组自查'), ('系统检测', '系统检测')], max_length=32, verbose_name='故障生成形式')),
                ('fault_code', models.CharField(max_length=32, verbose_name='故障代码')),
                ('fault_desc', models.TextField(blank=True, verbose_name='故障现象描述')),
                ('occur_time', models.DateTimeField(blank=True, null=True, verbose_name='发生时间')),
                ('ppl_traped', models.BooleanField(default=False, verbose_name='是否困人')),
                ('handle_status', models.CharField(blank=True, choices=[('未处理', '未处理'), ('处理中', '处理中'), ('已处理', '已处理')], default='未受理', max_length=32, verbose_name='处理状态')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='受理时间')),
                ('handle_result', models.TextField(blank=True, verbose_name='处理结果')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
                ('run_status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='故障时刻电梯运行状态')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Elevator', verbose_name='故障电梯')),
                ('execution_ppl', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '故障记录',
                'verbose_name_plural': '故障记录',
                'db_table': 'fault_record',
            },
        ),
    ]
