# Generated by Django 2.0.2 on 2018-03-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('call_number', models.CharField(blank=True, max_length=32, verbose_name='来电号码')),
                ('call_time', models.DateTimeField(blank=True, null=True, verbose_name='来电时间')),
                ('call_department', models.CharField(blank=True, max_length=64, verbose_name='来电科室')),
                ('call_reason', models.CharField(max_length=32, verbose_name='来电事由')),
                ('call_content', models.TextField(blank=True, max_length=512, verbose_name='来电明细')),
                ('recover_time', models.DateTimeField(blank=True, null=True, verbose_name='电梯恢复时间')),
                ('handle_result', models.TextField(blank=True, max_length=512, verbose_name='处理结果')),
                ('handle_status', models.CharField(blank=True, choices=[('待处理', '待处理'), ('处理中', '处理中'), ('已处理', '已处理')], default='待处理', max_length=32, verbose_name='处理状态')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Area', verbose_name='报修区域')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Elevator', verbose_name='报修电梯')),
                ('on_duty_ppl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='值班人员')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '电话记录',
                'verbose_name_plural': '电话记录',
                'db_table': 'call_record',
            },
        ),
        migrations.CreateModel(
            name='DutyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '值班记录',
                'verbose_name_plural': '值班记录',
                'db_table': 'duty_record',
            },
        ),
    ]
